### ISSUE TITLE
Updating the content

### ISSUE THREAD

**Issue by celikalp** [celikalp/aerocast#1]
1. As we have talked and temporarily agreed on the name Copia which is the goddest of abundance so we can update the page name and page header as Copia.
2. Description seems a bit misleading. We tell users when to buy the cheapest ticket. 
3. We may add our name on the front page as "Brought to you by ... , ... and ..."
4. We may update copyright text located footer.
5. As Taha said, supervisor, jury members and innovation expert info should be added.
6. You may update report names.
7. Background picture looks a bit irrelavent. We can update it to a more related pic which is commercial aircraft like Boing 777.

**Comment by atalbayrak** [comment]
1- Bitti
2- Bir şey uydurun güncellerim
3- bitti
4- bitti
5- isimler belli olsun biter
6- bitti
7- bitti
